description: This page should depict the changes made to the original repository and showcase the ability to create a site using GitHub Pages, according to the GitHub Pages skill check
author: Drzumeta
theme: minima
